# Theme Configuration
# ===================

theme:
  name: "default"

  default_appearance: "dark"
  default_palette: "snow-lynx"

  syntax_highlighting:
    theme: "auto"
    css_class_style: "semantic"

  features:
    - navigation.breadcrumbs
    - navigation.toc
    - navigation.toc.sticky
    - navigation.prev_next
    - navigation.back_to_top

    - content.code.copy
    - content.reading_time
    - graph.contextual

    - search
    - search.suggest
    - search.highlight

    - footer.social

    - accessibility.skip_link

  max_tags_display: 10
  popular_tags_count: 20

header:
  nav_position: center
  sticky: true
